In [11]:
import pandas as pd

In [34]:
df = pd.read_csv("weather_data.csv", parse_dates=["day"])

In [13]:
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [40]:
df.set_index("day", inplace=True)

In [15]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [16]:
df.fillna("0")

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04           0       9.0   Sunny
2017-01-05        28.0         0    Snow
2017-01-06           0       7.0       0
2017-01-07        32.0         0    Rain
2017-01-08           0         0   Sunny
2017-01-09           0         0       0
2017-01-10        34.1       8.1  Cloudy
2017-01-11        40.0      12.0   Sunny

In [17]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [18]:
df.fillna({
    'temperature': df.temperature.mean(),
    'windspeed': df.windspeed.mean(),
    'event': 'No Event'
})

            temperature  windspeed     event
day
2017-01-01        32.00       6.00      Rain
2017-01-04        33.22       9.00     Sunny
2017-01-05        28.00       8.42      Snow
2017-01-06        33.22       7.00  No Event
2017-01-07        32.00       8.42      Rain
2017-01-08        33.22       8.42     Sunny
2017-01-09        33.22       8.42  No Event
2017-01-10        34.10       8.10    Cloudy
2017-01-11        40.00      12.00     Sunny

In [23]:
df.ffill()

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        7.0   Sunny
2017-01-09         32.0        7.0   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [26]:
df.bfill(axis=1)

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04         9.0       9.0   Sunny
2017-01-05        28.0      Snow    Snow
2017-01-06         7.0       7.0     NaN
2017-01-07        32.0      Rain    Rain
2017-01-08       Sunny     Sunny   Sunny
2017-01-09         NaN       NaN     NaN
2017-01-10        34.1       8.1  Cloudy
2017-01-11        40.0      12.0   Sunny

In [27]:
df.ffill(limit=1)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        NaN   Sunny
2017-01-09          NaN        NaN   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [32]:
numeric_cols = df.select_dtypes(include='number').columns
df[numeric_cols] = df[numeric_cols].interpolate(method='linear')
df

            temperature  windspeed   event
day
2017-01-01         32.0      6.000    Rain
2017-01-04         30.0      9.000   Sunny
2017-01-05         28.0      8.000    Snow
2017-01-06         30.0      7.000     NaN
2017-01-07         32.0      7.275    Rain
2017-01-08         32.7      7.550   Sunny
2017-01-09         33.4      7.825     NaN
2017-01-10         34.1      8.100  Cloudy
2017-01-11         40.0     12.000   Sunny

In [35]:
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [41]:
df.dropna(how="all")

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [45]:
df.dropna(thresh=1)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [46]:
df.dropna(thresh=2)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-07         32.0        NaN    Rain
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny